version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.23.9
    restart: on-failure:0
    ports:
    - 8000:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    ports:
    - 8001:8080
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      ENABLE_CUDA: 1
      NVIDIA_VISIBLE_DEVICES: all
  vllm:
    image: vllm-cuda18.1
    ports:
      - 8002:8000
    build:
      context: vllm/
      dockerfile: Dockerfile
    volumes:
      - ./vllm/model-7b:/app/model-7b
    command: "--model /app/model-7b --dtype half --gpu-memory-utilization 0.99"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  dev-jupyter:
    image: rag-explore-dev
    ports:
      - 8888:8888
    container_name: dev-jupyter
    build:
      context: dev/
      dockerfile: Dockerfile
    volumes:
      - ./dev/data:/app/data


volumes:
    weaviate_data: